### ISSUE TITLE
Statsig React Native not working

### ISSUE THREAD

**Issue by sahil-ahuja-1** [statsig-io/statsig-feedback#32] opened 2022-11-08 20:28 UTC
Hello! StatSig is not working with React Native for me.

The app builds find but adding StatsigProvider causes the app to crash

I'm using react native version 0.67.3 and react version 17.0.2

![Simulator Screen Shot - iPhone 13 - 2022-11-08 at 15 24 53](https://user-images.githubusercontent.com/101741806/200668396-867db582-d8a6-4e1f-93de-f31aa354531d.png)

**Comment by sahil-ahuja-1** [comment] 2022-11-08 20:28
This has been happening for several months and has been a hard blocker from our company using your product. I'd appreciate any help getting this to work! Thanks :)

**Comment by ritvik-statsig** [comment] 2023-01-06 18:26
duplicate of https://github.com/statsig-io/react-native/issues/1

**Closed as completed by ritvik-statsig** 2023-01-06 18:26 UTC
