### ISSUE TITLE
[Bug][DartSDK] ParameterStore.get() fails to retrieve static string array values

### ISSUE THREAD

**Issue by OrcunJoyoLabs** [statsig-io/statsig-feedback#51] opened 2024-11-15 21:03 UTC
**Description**

When attempting to retrieve array values from Parameter Store using the Statsig Dart SDK (v1.2.1), the API consistently returns null or default values, even for the most basic retrieval attempts. This appears to be a fundamental issue with array handling.
The parameter "enabled_values" is configured as a static string array in Parameter Store with values like:
```json
[
  "xxxxxxxxxxxxxxxxxxxxxxx1",
  "xxxxxxxxxxxxxxxxxxxxxxx2",
  "xxxxxxxxxxxxxxxxxxxxxxx3",
  "xxxxxxxxxxxxxxxxxxxxxxx4",
  "xxxxxxxxxxxxxxxxxxxxxxx5"
]
```

**Current Behavior**

1. Basic retrieval returns null:
```dart
// Returns null
dynamic getValues() {
  final storeName = Statsig.getParameterStore("test_store");
  return storeName.get("enabled_values");
}
```
2. Direct casting to List<String> returns null:
```dart
// Returns null
List<String> getValues() {
  final storeName = Statsig.getParameterStore("test_store");
  return storeName.get("enabled_values") as List<String>;
}
```
3. Casting to List<dynamic> returns null:
```dart
// Returns null
List<String> getValues() {
  final storeName = Statsig.getParameterStore("test_store");
  return (storeName.get("enabled_values") as List<dynamic>).cast<String>();
}
```

4. Using default value returns only the default:
```dart
// Returns default value only
List<String> getValues() {
  final storeName = Statsig.getParameterStore("test_store");
  final defaultValue = ['123123'];
  return (storeName.get("enabled_values", defaultValue) as List<dynamic>)
      .cast<String>();
}
```

5. Explicit casting to List<String> using the API, throws
```dart
// Throws 'List<dynamic>' is not a subtype of type 'List<String>' in type cast
List<String>? getValues() {
  final storeName = Statsig.getParameterStore("test_store");
  return storeName.get<List<String>>("enabled_values");
}
```

6. Current workaround (explicit List<dynamic> typing) (Works):
```dart
// Works but requires unintuitive casting
List<String> getValues() {
  final storeName = Statsig.getParameterStore("test_store");
  final defaultValue = ['123123'] as List<dynamic>;
  return (storeName.get("enabled_values", defaultValue) as List<dynamic>)
      .cast<String>();
}
```

**Expected Behavior**

- The basic get() call should return the configured array value from the Parameter Store.
- Casting should be intuitive

The basic get() call should return the configured array value from the Parameter Store.

**Environment**

Statsig Dart SDK Version: 1.2.1
Dart SDK Version: 3.5.3
Platform: Dart/Flutter
Parameter Store Configuration: Static string array value

**Comment by tore-statsig** [comment] 2024-11-18 23:28
Thanks for the report, we are taking a look

**Comment by tore-statsig** [comment] 2024-11-19 00:25
Interesting, it looks like the only difference between your callsite and our internal test for this is specifying a default value.  So we do:

```
var store =
      Statsig.getParameterStore(name, disableExposureLogging: noExposure);
return store.get("parameter_name", []);
```

So ill continue to look at this in the case a default is not provided.  But if you provide even just an empty array, this should work

**Comment by OrcunJoyoLabs** [comment] 2024-11-19 00:32
Thank you for the response @tore-statsig. 

Have you had a chance to take a look at the cases I have shared above? If you look at example #4, it returns only the default value when I provide a default, it never returns the existing value from the store.

Also there's the broader problem of typing / casting here. It's super confusing and error prone, as I shared with other examples. store.get("parameter_name", []); completely loses the type, and casting messes things up. Ideally all 6 cases above should return me the correct value.

**Comment by OrcunJoyoLabs** [comment] 2024-11-19 00:38
I will actually give you a yet another interesting data point

Try passing a non-empty list as the default value e.g.

```dart
var store =
      Statsig.getParameterStore(name, disableExposureLogging: noExposure);
return store.get("parameter_name", ["123"]);
``` 

This will always return you the default value you passed.

**Comment by tore-statsig** [comment] 2024-11-21 23:42
There was a bug related to not providing a default value. This was patched in v1.2.2

https://github.com/statsig-io/dart-sdk/releases/tag/v1.2.2

We were unable to reproduce the last example you provided with a non-empty default array.  We also havent exhaustively tried all variants you sent above, but the recent bugfix should be enough to unblock right now while we follow up on the rest

**Comment by OrcunJoyoLabs** [comment] 2024-11-22 02:08
This is great! The fix works for us with no default!  Interesting. Happy to help provide store name etc. for internal debugging: 

```dart
storeName.get("enabled_values", ['default_value']); => always returns ['default_value']
storeName.get("enabled_values", ['default_value'] as List<dynamic>); => works properly (returns enabled values as it should)
```

Feeling there's some casting magicary going on.

**Comment by tore-statsig** [comment] 2024-12-06 23:39
We've added a list<dynamic> getter to parameter stores in the latest version as well: `getArray`

This should make it more explicit.  Going to close this out now

**Closed as completed by tore-statsig** 2024-12-06 23:39 UTC
